language: php
sudo: required

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - |
    if [ "x$COVERAGE" != "xyes" ]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
    fi

install:
  - travis_retry composer -n update --prefer-dist --no-interaction $IGNORE_PLATFORM_REQS

jobs:
  allow_failures:
    - php: nightly
    - stage: Mutation

  include:
    - stage: Test PHP 7.2
      php: 7.2
      env: COVERAGE=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        - bash <(curl -s https://codecov.io/bash)
    - stage: Coding standard
      php: 7.2
      script:
        - composer cs-check
    - stage: Static analysis
      php: 7.2
      script:
        - composer phpstan
    - stage: Test PHP7.1
      php: 7.2
      env: COVERAGE=false
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml
    - stage: Mutation
      php: 7.2
      env: COVERAGE=true
      script:
        - ./vendor/bin/infection --configuration=.travis/infection.travis.json --test-framework=phpunit --min-msi=55 --min-covered-msi=65 --threads=4
    - stage: Test PHP Nightly
      php: nightly
      env: COVERAGE=false IGNORE_PLATFORM_REQS="--ignore-platform-reqs"
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml

