language: php
sudo: required

cache:
    directories:
        - vendor
        - $HOME/.composer/cache
        - .travis/downloads
        - .travis/ffmpeg-release-64bit-static

before_install:
  - |
    if [ "x$COVERAGE" != "xyes" ]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
    fi
  - |
    if [ "x$INSTALL_FFMPEG" != "xyes" ]; then
      .travis/travis-install-ffmpeg.sh
    fi

install:
  - |
    if [ "x$IGNORE_PLATFORM_REQS" != "xyes" ]; then
      travis_retry composer -n update --prefer-dist --no-interaction
    else
      travis_retry composer -n update --prefer-dist --no-interaction --ignore-platform-reqs
    fi


jobs:
  allow_failures:
    - php: nightly
    - stage: Mutation

  include:
    - stage: Test PHP 7.2
      php: 7.2
      env: COVERAGE=yes INSTALL_FFMPEG=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        - bash <(curl -s https://codecov.io/bash)
    - stage: Coding standard
      php: 7.2
      script:
        - composer cs-check
    - stage: Static analysis
      php: 7.2
      script:
        - composer phpstan
    - stage: Test PHP7.1 (unit tests only)
      php: 7.1
      env: COVERAGE=false
      script:
        - ./vendor/bin/phpunit --testsuite unit -v -c .travis/phpunit.xml
    - stage: Mutation
      php: 7.2
      env: COVERAGE=true INSTALL_FFMPEG=yes
      script:
        - ./vendor/bin/infection --configuration=.travis/infection.travis.json --test-framework=phpunit --min-msi=55 --min-covered-msi=65 --threads=4
    - stage: Test PHP Nightly (unit tests only)
      php: nightly
      env: COVERAGE=false IGNORE_PLATFORM_REQS=yes
      script:
        - ./vendor/bin/phpunit --testsuite unit -v -c .travis/phpunit.xml

