language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 7.1
    - php: 7.2
      env:
        - SEND_COVERAGE=true
        - CHECK=true
        - INFECTION=true
    - php: nightly
      env:
        - IGNORE_PLATFORM_REQS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

before_script:
  # -------------------------------------------------------------------------
  # Step 1: FFMpeg installation
  # -------------------------------------------------------------------------
  #- sudo add-apt-repository -y ppa:mc3man/trusty-media
  #- sudo apt-get -qq update
  #- sudo apt-get install -y ffmpeg
  - .travis/travis-install-ffmpeg.sh
  # -------------------------------------------------------------------------
  # Step 2: Regular composer install
  # -------------------------------------------------------------------------
  - composer install --no-interaction $IGNORE_PLATFORM_REQS
script:
  - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
  - if [[ $CHECK == true ]]; then composer check; fi
  - if [[ $INFECTION == true ]]; then ./vendor/bin/infection --configuration=.travis/infection.travis.json --test-framework=phpunit --min-msi=55 --min-covered-msi=65 --threads=4; fi

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
